version: "2"

services:
    postgres:   
        image: yin2/postgres-9.3:latest
        ports:
            - 5432:5432
        container_name: "postgres"
        networks:
            - app-net

    elasticsearch:
        image: yin2/elasticsearch-1.7:1.7.3
        ports:
            - 9200:9200
        container_name: "elasticsearch"
        networks:
            - app-net

    annotator-store:
        image: yin2/annotator-store
        environment:
            - ELASTICSEARCH_HOST=elasticsearch
        depends_on: 
            - "elasticsearch"
        command: bash -c "sleep 10; python /home/yin2/annotator-store/run.py"
        ports:
            - 5000:5000
        container_name: "annotator-store"
        networks:
            - app-net

    apache2:
        image: yin2/apache2:2.4
        ports:
            - 80:80    
        container_name: "apache2"
        networks:
            - app-net

    dbmi-annotator:
        build: .
        ports:
            - 3000:3000
        environment:
            - PGHOST=postgres
            - PGDATABASE=dbmiannotator
            - PGUSER=dbmiannotator
            - ELASTICSEARCH_HOST=elasticsearch
            - APACHE2_HOST=apache2
        depends_on: 
            - "postgres"
        container_name: "dbmi-annotator"
        networks:
            - app-net

networks:
    app-net:
        driver: bridge